# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Pod-BBCode
version:      1.5
version_from: lib/Pod/BBCode.pm
installdirs:  site
requires:
    Pod::Parser:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.28
